### ISSUE TITLE
Link typo hypervsior

### ISSUE THREAD

**Issue by Mirdinus** [cloud-hypervisor/cloud-hypervisor.github.io#16]
## Description

Hi, there is a typo on the [website](https://www.cloudhypervisor.org/) in the "Github" link.
It links to https://github.com/cloud-hypervsior instead of https://github.com/cloud-hypervisor

### Steps to reproduce

Go to https://www.cloudhypervisor.org
Click on link "Github" under "Get started" button.

### Expected result

Getting to Githuborg page

### Actual result

Github 404 error

### Environment

N/A

**Comment by wikix** [comment]
same issue found
